name: kl1mt0p_test
on:  
  push: 
    branches: [ "develop" ] 
  pull_request: 
    branches: [ "develop" ] 
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - uses: actions/checkout@v3 
      - name: open dir
        run: cd $GITHUB_WORKSPACE
      - name: main_test
        run: echo numbers1.txt | python -m unittest functions_test.py | python -m unittest empty_test.py | python -m unittest speed_test.py | Python functions_test.py >> report1.txt | Python empty_test.py >> report2.txt | Python speed_test.py >> report3.txt
      - name: fail 
        uses: appleboy/telegram-action@master 
        if: failure() 
        with: 
          to: ${{ secrets.TELEGRAM_TO }} 
          token: ${{ secrets.TELEGRAM_TOKEN }} 
          message: | 
               Вы где то налажали :(
          document: report1.txt | report2.txt | report3.txt
      - name: ok 
        uses: appleboy/telegram-action@master 
        if: success() 
        with: 
          to: ${{ secrets.TELEGRAM_TO }} 
          token: ${{ secrets.TELEGRAM_TOKEN }} 
          message: | 
            Вы справились юхууууу
